export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_PENDING = 'FETCHING_DATA_PENDING';
export const FETCHING_DATA_FULFILLED = 'FETCHING_DATA_FULFILLED';
export const FETCHING_DATA_REJECTED = 'FETCHING_DATA_REJECTED';
